name: 'system_information_dart'
description: 'A library for get system info detail like ram or proccesor ram in dart support client side and server side.'
version: '0.0.0'
homepage: 'https://github.com/azkadev/azkadev'
repository: 'https://github.com/azkadev/system_information'
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies: {}
dev_dependencies:
  lints: '^4.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
