name: 'system_information_flutter'
description: 'A System Information library for help you get information device'
version: '0.0.12'
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: 'flutter'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
flutter:
  plugin:
    platforms:
      android:
        package: 'global_corporation.general_developer.azkadev.system_information_flutter'
        pluginClass: 'SystemInformationFlutterPlugin'
      web: null
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
repository: 'https://github.com/azkadev/system_information'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
homepage: 'https://youtube.com/@azkadev'
project:
  type: ''
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  windows: null
  web: null
