name: 'system_information_flutter'
description: 'A new Flutter plugin project.'
version: '0.0.1'
homepage: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  plugin_platform_interface: '^2.0.2'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^4.0.0'
flutter: 
  plugin: 
    platforms: 
      android: 
        package: 'global_corporation.general_developer.azkadev.system_information_flutter'
        pluginClass: 'SystemInformationFlutterPlugin'
      ios: 
        pluginClass: 'SystemInformationFlutterPlugin'
dependency_overrides: 
  pointycastle: '3.8.0'
funding: []
