name: 'system_information'
description: 'A library for get system info detail like ram or proccesor ram in dart support client side and server side.'
version: '0.0.6'
homepage: 'https://github.com/azkadev/azkadev'
repository: 'https://github.com/azkadev/system_information'
environment:
  sdk: '>=3.6.0 <4.0.0'
platforms:
  android: null
  linux: null
  ios: null
  web: null
  macos: null
  windows: null
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependencies:
  flutter:
    sdk: 'flutter'
  io_universe: '^0.0.2'
  general_lib: '^0.0.52'
  path: '^1.9.0'
  system_information_flutter: '^0.0.6'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
